######################## LANGUAGE ################################
LANGUAGE="fr"

######################## HOSTS LIST ##############################
## Nodes to be handled by the script / FQDN
## Used by RKE2 when generating TLS certs
HOST_LIST="ranch1.domain,ranch2.domain,ranch3.domain"

######################## IF AIRGAP SETUP #########################
## Airgap deployment
AIRGAP_DEPLOY="0"	# 1=airgap enabled / 0=airgap disabled
AIRGAP_REGISTRY_URL="registry.domain:5000"
AIRGAP_REGISTRY_CACERT=""
# Use insecure registry
AIRGAP_REGISTRY_INSECURE="1" # 1=insecure / 0=secured
# Optional user/password
AIRGAP_REGISTRY_USER=""
AIRGAP_REGISTRY_PASSWD=""
## Docker version to use for Airgap image synchronization (RHEL/CentOS)
DOCKER_VERSION="20.10"  # options [20.10|23.0|24.0]

######################## IF PROXY SETUP ##########################
## Proxy settings
PROXY_DEPLOY="0"	# 1=proxy enabled / 0=proxy disabled
_HTTP_PROXY="admin:3128"
_HTTPS_PROXY="admin:3128"
_NO_PROXY=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,cattle-system.svc,.svc,.cluster.local,.zypp.lo

######################## SELECT VERSIONS #########################
## RKE2, Rancher and Helm versions to deploy
HELM_VERSION="3.8.2"
RKE2_VERSION="v1.26.9+rke2r1"
CERTMGR_VERSION="v1.12.5"
RANCHER_VERSION="2.7.6"

######### RANCHER MGMT SERVER CERTIFICATE AND PRIVATE CA #########
## Rancher TLS configuration. Available options are [rancher,secret,external]
## - rancher  :  Self-signed certificate are generated by cert-manager (default)
## - secret   :  User provided certificate. Certificate (tls.crt) and key (tls.key) must be placed in working directory
## - external :  External TLS termination
TLS_SOURCE="rancher"
## Private CA (cacerts.pem must be placed in working directory)
PRIVATE_CA="0"

######################## FQDNs & DOMAINs #########################
## Rancher Management Load balancer FQDN (redirect to RKE nodes hosting Rancher)
LB_RANCHER_FQDN="rancher.domain"
## RKE2 KUBE-VIP configuration (leave empty if you do not want to use kube-vip)
## RKE2_VIP_FQDN and RKE2_VIP_IP are both mandatory for kube-vip deployment.
RKE2_VIP_IP=192.168.100.27
RKE2_VIP_FQDN="ranch-vip.domain"
RKE2_VIP_INTERFACE="eth0"
