# Base LDIF — OUs and Groups for Rancher OIDC
# Generated by 01-deploy-openldap.sh — do not edit manually

# Organizational Units
dn: ou=People,__LDAP_BASE_DN__
objectClass: organizationalUnit
ou: People

dn: ou=Groups,__LDAP_BASE_DN__
objectClass: organizationalUnit
ou: Groups

# Groups
__GROUPS__
