apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CAPI_CLUSTER_NAME}
  namespace: ${CAPI_NAMESPACE}
  labels:
    ccm: external
    csi: external
    cni: external
spec:
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: RKE2ControlPlane
    name: ${CAPI_CP_NAME}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: HarvesterCluster
    name: ${CAPI_HV_CLUSTER}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: HarvesterCluster
metadata:
  name: ${CAPI_HV_CLUSTER}
  namespace: ${CAPI_NAMESPACE}
spec:
  identitySecret:
    name: ${CAPI_IDENTITY_SECRET}
    namespace: ${CAPI_NAMESPACE}
  loadBalancerConfig:
    ipamType: ${CAPI_LB_IPAM}
    listeners:
      - name: rke2-server
        port: 9345
        backendPort: 9345
        protocol: TCP
  targetNamespace: default
